// Supabase Database Types
// This file will be generated by Supabase CLI in production
// For now, these are manually defined based on PALLETPULSE_ONESHOT_CONTEXT.md schema

export type ItemCondition =
  | 'new'
  | 'open_box'
  | 'used_good'
  | 'used_fair'
  | 'damaged'
  | 'for_parts'
  | 'unsellable';

export type ItemStatus = 'unprocessed' | 'listed' | 'sold';

export type PalletStatus = 'unprocessed' | 'processing' | 'completed';

export type SourceType =
  | 'pallet'
  | 'thrift'
  | 'garage_sale'
  | 'retail_arbitrage'
  | 'mystery_box'
  | 'other';

export type ExpenseCategory =
  | 'supplies'
  | 'gas'
  | 'storage'
  | 'fees'
  | 'other';

export type NotificationType =
  | 'stale_inventory'
  | 'pallet_milestone'
  | 'weekly_summary'
  | 'subscription_reminder'
  | 'limit_warning'
  | 'system';

export type SubscriptionStatus = 'active' | 'canceled' | 'past_due';

export type BillingCycle = 'monthly' | 'annual';

export type PayoutStatus = 'pending' | 'processing' | 'completed' | 'failed';

export type PayoutMethod = 'stripe' | 'paypal';

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          subscription_tier: 'free' | 'starter' | 'pro' | 'enterprise';
          subscription_status: SubscriptionStatus;
          affiliate_code: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
          subscription_tier?: 'free' | 'starter' | 'pro' | 'enterprise';
          subscription_status?: SubscriptionStatus;
          affiliate_code?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          subscription_tier?: 'free' | 'starter' | 'pro' | 'enterprise';
          subscription_status?: SubscriptionStatus;
          affiliate_code?: string | null;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          stale_threshold_days: number;
          storage_locations: string[];
          default_sales_tax_rate: number | null;
          mileage_rate: number;
          include_unsellable_in_cost: boolean;
          notification_stale_inventory: boolean;
          notification_weekly_summary: boolean;
          notification_pallet_milestones: boolean;
          email_weekly_summary: boolean;
          email_stale_digest: boolean;
          email_monthly_report: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stale_threshold_days?: number;
          storage_locations?: string[];
          default_sales_tax_rate?: number | null;
          mileage_rate?: number;
          include_unsellable_in_cost?: boolean;
          notification_stale_inventory?: boolean;
          notification_weekly_summary?: boolean;
          notification_pallet_milestones?: boolean;
          email_weekly_summary?: boolean;
          email_stale_digest?: boolean;
          email_monthly_report?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stale_threshold_days?: number;
          storage_locations?: string[];
          default_sales_tax_rate?: number | null;
          mileage_rate?: number;
          include_unsellable_in_cost?: boolean;
          notification_stale_inventory?: boolean;
          notification_weekly_summary?: boolean;
          notification_pallet_milestones?: boolean;
          email_weekly_summary?: boolean;
          email_stale_digest?: boolean;
          email_monthly_report?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      pallets: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          supplier: string;
          source_type: string;
          purchase_cost: number;
          sales_tax: number;
          purchase_date: string;
          status: PalletStatus;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          supplier: string;
          source_type?: string;
          purchase_cost: number;
          sales_tax?: number;
          purchase_date?: string;
          status?: PalletStatus;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          supplier?: string;
          source_type?: string;
          purchase_cost?: number;
          sales_tax?: number;
          purchase_date?: string;
          status?: PalletStatus;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      items: {
        Row: {
          id: string;
          user_id: string;
          pallet_id: string | null;
          name: string;
          description: string | null;
          quantity: number;
          condition: ItemCondition;
          retail_price: number | null;
          listing_price: number | null;
          sale_price: number | null;
          purchase_cost: number | null;
          allocated_cost: number | null;
          storage_location: string | null;
          status: ItemStatus;
          listing_date: string | null;
          sale_date: string | null;
          sales_channel: string | null;
          barcode: string | null;
          source_type: SourceType;
          source_name: string | null;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pallet_id?: string | null;
          name: string;
          description?: string | null;
          quantity?: number;
          condition?: ItemCondition;
          retail_price?: number | null;
          listing_price?: number | null;
          sale_price?: number | null;
          purchase_cost?: number | null;
          allocated_cost?: number | null;
          storage_location?: string | null;
          status?: ItemStatus;
          listing_date?: string | null;
          sale_date?: string | null;
          sales_channel?: string | null;
          barcode?: string | null;
          source_type?: SourceType;
          source_name?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pallet_id?: string | null;
          name?: string;
          description?: string | null;
          quantity?: number;
          condition?: ItemCondition;
          retail_price?: number | null;
          listing_price?: number | null;
          sale_price?: number | null;
          purchase_cost?: number | null;
          allocated_cost?: number | null;
          storage_location?: string | null;
          status?: ItemStatus;
          listing_date?: string | null;
          sale_date?: string | null;
          sales_channel?: string | null;
          barcode?: string | null;
          source_type?: SourceType;
          source_name?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      item_photos: {
        Row: {
          id: string;
          item_id: string;
          user_id: string;
          storage_path: string;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          user_id: string;
          storage_path: string;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          user_id?: string;
          storage_path?: string;
          display_order?: number;
          created_at?: string;
        };
      };
      expenses: {
        Row: {
          id: string;
          user_id: string;
          pallet_id: string | null;
          amount: number;
          category: ExpenseCategory;
          description: string | null;
          expense_date: string;
          receipt_photo_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pallet_id?: string | null;
          amount: number;
          category: ExpenseCategory;
          description?: string | null;
          expense_date?: string;
          receipt_photo_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pallet_id?: string | null;
          amount?: number;
          category?: ExpenseCategory;
          description?: string | null;
          expense_date?: string;
          receipt_photo_path?: string | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationType;
          title: string;
          body: string;
          data: Record<string, unknown> | null;
          is_read: boolean;
          created_at: string;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: NotificationType;
          title: string;
          body: string;
          data?: Record<string, unknown> | null;
          is_read?: boolean;
          created_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: NotificationType;
          title?: string;
          body?: string;
          data?: Record<string, unknown> | null;
          is_read?: boolean;
          created_at?: string;
          read_at?: string | null;
        };
      };
    };
  };
}

// Helper types for easier access
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Convenient type aliases
export type User = Tables<'users'>;
export type UserSettings = Tables<'user_settings'>;
export type Pallet = Tables<'pallets'>;
export type Item = Tables<'items'>;
export type ItemPhoto = Tables<'item_photos'>;
export type Expense = Tables<'expenses'>;
export type Notification = Tables<'notifications'>;
